export const browserRoutes = {
  HOME: '/',
  PROFILE: '/profile',
  SUMMARY: '/summary',
  MYQUESTIONS: '/myquestions',
  MYANSWERS: '/myanswers',
  SIGNIN: '/signin',
  SIGNUP: '/signup',
  ASK_QUESTIONS: '/askquestion',
  QUESTION_DETAILS: '/question',
  WRITE: '/write',
  SETTINGS: '/settings',
  USERSLIST: '/users',
  USER: '/user',
  TUTORIAL: '/tutorial',
};
