export const browserRoutes = {
  HOME: '/',
  ABOUT: '/about',
  PROFILE: '/profile',
  SUMMARY: '/summary',
  MYQUESTIONS: '/myquestions',
  MYANSWERS: '/myanswers',
  SIGNIN: '/signin',
  SIGNUP: '/signup',
  ASK_QUESTIONS: 'askquestion',
  QUESTION_DETAILS: '/question',
  QUESTION_DETAILS2: '/question',
  WRITE: '/write',
  SETTINGS: '/settings',
  DEVELOPERS: '/developers',
  TUTORIAL: '/tutorial',
  KNOWLEDGE: '/user/knowledge',
  FOLLOWING: '/following',
  MESSAGE: '/message',
  SNIPPETS: '/snippets',
  MYKNOWLEDGE: 'myknowledge',
  ALLQUESTIONS: '/allquestions',
};
