export const browserRoutes = {
  HOME: '/',
  PROFILE: '/profile',
  SUMMARY: '/summary',
  MYQUESTIONS: '/myquestions',
  MYANSWERS: '/myanswers',
  SIGNIN: '/signin',
  SIGNUP: '/signup',
  ASK_QUESTIONS: '/askquestion',
  QUESTION_DETAILS: '/question',
  WRITE: '/write',
  SETTINGS: '/settings',
  DEVELOPERS: '/developers',
  TUTORIAL: '/tutorial',
  KNOWLEDGE: '/knowledge',
  FOLLOWING: '/following',
  MESSAGE: '/message',
  SNIPPETS: '/snippets',
};
