export const authRoutes = {
  SIGNUP: `/users`,
  SIGNIN: `/users/login`,
  ASK_QUESTION: `/questions`,
  GET_QUESTIONS: `/questions`,
  MY_QUESTIONS: `/questions/myquestions`,
  MY_ANSWERS: `/answers/myanswers`,
  MY_KNOWLEDGE: `/knowledge/myknowledge`,
  SUBMIT_ANSWER: `/answers`,
  GET_ANSWERS: `/answers`,
  UPDATE_PROFILE: '/users/profile',
  ADD_COMMENT: '/answers/',
  COMMENTS: '/comments/get',
  KNOWLEDGE: '/knowledge',
  GET_KNOWLEDGE: '/users/knowledge',
  ADD_VOTE: '/answers/vote',
  TOP_DEVS: '/users/top',
  CANVOTE: '/questions/status/canvote',
  FOLLOW: '/users/follow',
  MYFOLLOWING: '/users/myfollowings',
  ISFOLLOW: '/users/isFollow',
  NOTIFICATION: '/users/notification',
  QUOTE: '/users/message',
  SNIPPET: '/snippets',
  LANGUAGE: '/admin/tag',
  KNOWLEDGE_COUNT: '/knowledge/count/user',
};
